import Head from "next/head";
import { Center, Container, styled, Typography } from "@aura-ui/react";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Loader } from "@/ui/Loader";
import { AudioPlayer } from "@/modules/AudioPlayer/containers/AudioPlayer";

const Main = styled("main", {
  display: "flex",
  alignItems: "center",
  flexDirection: "column",
  justifyContent: "center",
  width: "100%",
  height: "100%",
});

const links: { name: string; desc: string; url: string }[] = [
  {
    name: "Wiki",
    desc: "Find in-depth information about the Arweave protocol.",
    url: "https://arwiki.wiki/",
  },
  {
    name: "Cookbook",
    desc: "Learn how to go from 0-1 with building Permaweb apps.",
    url: "https://cookbook.arweave.dev/",
  },
  {
    name: "Get a Wallet",
    desc: "Get an Arweave wallet to start uploading data to the Permaweb.",
    url: "https://www.arconnect.io/",
  },
  {
    name: "VouchDao",
    desc: "Vouch for your identity on the Permaweb!",
    url: "https://vouchdao.xyz/",
  },
];

const LinkCard = ({
  name,
  url,
  desc,
}: {
  name: string;
  url: string;
  desc: string;
}) => (
  <Container
    css={{
      maxW: "24ch",
      br: "$3",
      boxShadow: "0 0 0 1px $colors$slate6",
      p: "$5",

      "&:hover": {
        backgroundColor: "$slate2",
        boxShadow: "0 0 0 1px $colors$slate7",
      },
    }}
    as="a"
    href={url}
    target="_blank"
    rel="noopener noreferrer"
  >
    <Typography contrast="hiContrast" size="4" weight="6">
      {name} <span>-&gt;</span>
    </Typography>
    <Typography>{desc}</Typography>
  </Container>
);

export default function Home() {
  const [txid, setTxid] = useState<string>();
  const router = useRouter();

  useEffect(() => {
    console.log(router.query.tx);

    if (router.query.tx) {
      setTxid(router.query.tx as string);
    } else {
      console.log("No txid provided");
    }
  }, [router.query.tx]);

  const testId = "KDHGLGjoe1oGPOCyUeLQ1vUA407gauX-J_QApwhac7c";

  return (
    <>
      <Head>
        <title>Permaweb audio renderer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Center
        css={{
          // backgroundColor: "$blackA1",
          height: "100%",
        }}
      >
        {txid ? <AudioPlayer txid={txid} /> : <Loader />}
        {/* <AudioPlayer txid={txid} /> */}
      </Center>
    </>
  );
}
