import Head from "next/head";
import { Center } from "@aura-ui/react";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Loader } from "@/ui/Loader";
import { AudioPlayer } from "@/modules/AudioPlayer/containers/AudioPlayer";

export default function Home() {
  const [txid, setTxid] = useState<string>();
  const router = useRouter();

  useEffect(() => {
    // console.log(router.query.tx);

    if (router.query.tx) {
      setTxid(router.query.tx as string);
    } else {
      console.log("No txid provided");
    }
  }, [router.query.tx]);

  const testId = "KDHGLGjoe1oGPOCyUeLQ1vUA407gauX-J_QApwhac7c";

  return (
    <>
      <Head>
        <title>Permaweb audio renderer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Center
        css={{
          height: "100%",
        }}
      >
        {txid ? <AudioPlayer txid={txid} /> : <Loader />}
      </Center>
    </>
  );
}
